### ISSUE TITLE
java.lang.NoClassDefFoundError on versions above 6.0.0

### ISSUE THREAD

**Issue by mcorner** [twilio/video-quickstart-android#623]
### Description

When upgrading past 6.0.0 we get java.lang.NoClassDefFoundError when launching the app.  While the crash log seems unrelated to Twilio, we only get this when upgrading to 6.1 and above and we don't get it on 6.0 and below.  I am wondering if there might be some kind of gradle or buildtools incompatibility?

### Steps to Reproduce

This may be specific to our app, but upgrade from 6.0.0 to 6.1 or beyond and then launch the app.

#### Code

We can provide code as needed.

#### Expected Behavior

Not crash.

#### Actual Behavior

Crashes with java.lang.NoClassDefFoundError

--------- beginning of crash
03-08 17:07:58.775  6668  6668 E AndroidRuntime: FATAL EXCEPTION: main
03-08 17:07:58.775  6668  6668 E AndroidRuntime: Process: REDACTED, PID: 6668
03-08 17:07:58.775  6668  6668 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/collection/ArrayMap;
03-08 17:07:58.775  6668  6668 E AndroidRuntime: 	at com.google.firebase.FirebaseApp.<clinit>(FirebaseApp.java:102)
03-08 17:07:58.775  6668  6668 E AndroidRuntime: 	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:240)
03-08 17:07:58.775  6668  6668 E AndroidRuntime: 	at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:51)
03-08 17:07:58.775  6668  6668 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1917)
03-08 17:07:58.775  6668  6668 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1892)
03-08 17:07:58.775  6668  6668 E AndroidRuntime: 	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:45)
03-08 17:07:58.775  6668  6668 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6239)
03-08 17:07:58.775  6668  6668 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:5805)
03-08 17:07:58.775  6668  6668 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5722)
03-08 17:07:58.775  6668  6668 E AndroidRuntime: 	at android.app.ActivityThread.-wrap1(Unknown Source:0)
03-08 17:07:58.775  6668  6668 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
03-08 17:07:58.775  6668  6668 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-08 17:07:58.775  6668  6668 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
03-08 17:07:58.775  6668  6668 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
03-08 17:07:58.775  6668  6668 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-08 17:07:58.775  6668  6668 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
03-08 17:07:58.775  6668  6668 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
03-08 17:07:58.775  6668  6668 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.collection.ArrayMap" on path: DexPathList[[zip file "/system/framework/android.test.mock.jar", zip file "/system/framework/android.test.runner.jar", zip file "/data/app/REDACTED-5zD0_YX8QbbPRBHVnqrM8g==/base.apk"],nativeLibraryDirectories=[/data/app/REDACTED-5zD0_YX8QbbPRBHVnqrM8g==/lib/x86, /data/app/REDACTED-5zD0_YX8QbbPRBHVnqrM8g==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
03-08 17:07:58.775  6668  6668 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
03-08 17:07:58.775  6668  6668 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
03-08 17:07:58.775  6668  6668 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
03-08 17:07:58.775  6668  6668 E AndroidRuntime: 	... 17 more
03-08 17:07:58.784  1639  6609 W ActivityManager:   Force finishing activity REDACTED/.MainActivity
03-08 17:07:58.796  1639  1654 I ActivityManager: Showing crash dialog for package REDACTED u0

#### Reproduces how Often

100%

#### Logs

See above### Versions

All relevant version information for issue.

#### Video Android SDK

6.1.0 and above

#### Android API

      buildToolsVersion = "29.0.2"
      minSdkVersion = 21
      compileSdkVersion = 29
      targetSdkVersion = 29

        classpath("com.android.tools.build:gradle:3.5.4")
        classpath 'com.google.gms:google-services:4.2.0'

distributionUrl=https\://services.gradle.org/distributions/gradle-6.2-all.zip

#### Android Device

simulator

**Comment by Alton09** [comment]
Hi @mcorner . From looking at the exception, it appears that this is dependency issue in your application. I have verified this by adding the androidx.collections class `ArrayMap` to the `RoomActivity` in the [Twilio Video Android App](https://github.com/twilio/twilio-video-app-android) using SDK version `6.2.0` and no crash occurs. You may want to double check to ensure that you have successfully migrated your application to androidx and have included the androidx core library which contains the `ArrayMap` class. Thanks!
