### ISSUE TITLE
No static method create()Lorg/webrtc/EglBase; in quickStart & quickStartKotlin

### ISSUE THREAD

**Issue by funkyidol** [twilio/video-quickstart-android#430]
### Description

Both quickStart & quickStartAndroid crash immediately after taking camera and mic permissions with the following error log

```
java.lang.NoSuchMethodError: No static method create()Lorg/webrtc/EglBase; in class Lorg/webrtc/EglBase; or its super classes (declaration of 'org.webrtc.EglBase' appears in /data/app/com.twilio.video.quickstart.kotlin-h1xlP3VlqsUneVj80KRxsw==/base.apk)
        at com.twilio.video.EglBaseProvider.<init>(EglBaseProvider.java:93)
        at com.twilio.video.EglBaseProvider.instance(EglBaseProvider.java:37)
        at com.twilio.video.MediaFactory.instance(MediaFactory.java:50)
        at com.twilio.video.LocalAudioTrack.create(LocalAudioTrack.java:99)
        at com.twilio.video.LocalAudioTrack.create(LocalAudioTrack.java:43)
        at com.twilio.video.quickstart.kotlin.VideoActivity.createAudioAndVideoTracks(VideoActivity.kt:569)
        at com.twilio.video.quickstart.kotlin.VideoActivity.onRequestPermissionsResult(VideoActivity.kt:437)
        at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7954)
        at android.app.Activity.dispatchActivityResult(Activity.java:7776)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4615)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4015)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4058)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1960)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7081)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

Tried deleting global and local `.gradle` folders but didnt help

### Versions

All relevant version information for issue.

#### Video Android SDK

4.3.0

#### Android API

Android API 28

#### Android Device

Samsung SM-J600
Emulator image API 28 x86_64
One Plus 5

**Comment by funkyidol** [comment]
**Resolved**

I think it was because I was using the latest Android Studio 3.5 RC2 with the latest RC Gradle Plugin. I deleted the complete project, did a fresh checkout and used Android Studio 3.4.2 stable to open the project. Just updated the kotlin version to 1.3.10 & Gradle Plugin to 5.1.1 and it works now

**Comment by tuckercr** [comment]
I am having this issue, using Android Studio 3.5 (now a stable release), 'com.android.tools.build:gradle:3.5.0' and Gradle 5.4.1 to build.

**Comment by shaunpanjabi** [comment]
> I am having this issue, using Android Studio 3.5 (now a stable release), 'com.android.tools.build:gradle:3.5.0' and Gradle 5.4.1 to build.

Also seeing this issue. Haven't found a solution yet

**Comment by tanaymondal** [comment]
facing the same issue on Android Studio 3.5
Have anyone found any solution?

**Comment by tanaymondal** [comment]
problem resolved after going back to Android Studio 3.4.2

**Comment by aaalaniz** [comment]
Hey @tuckercr @shaunpanjabi @tanaymondal 

We are investigating this issue.

Thank you

**Comment by m-usmankhan** [comment]
Solved for me.
Go to project/build.gradle file, and downgrade gradle to 3.4.2: 
        classpath 'com.android.tools.build:gradle:3.4.2'

**Comment by tuckercr** [comment]
@m-usmankhan downgrading is a short term solution (which we too have used in our app) but sooner or later we will need Gradle to be current.

**Comment by Alton09** [comment]
Another work-around we have found is to increase the min SDK version to 21. This allows you to use the 3.5.0 Gradle plugin and 5.4.1+ Gradle versions.

**Comment by ayavilevich** [comment]
Happens here too after a Gradle upgrade.
Strangely, the crash only happens when I install the app by using the APK. If I run from Android Studio then it works fine.

**Comment by shaunpanjabi** [comment]
@ayavilevich was your apk using proguard? I saw the same issue where it was crashing only on release builds.

**Comment by Alton09** [comment]
We went ahead and created an issue within Google issue tracker [here](https://issuetracker.google.com/140508065). It appears that there is an issue with how D8 is desugaring WebRTC on the latest Android Gradle plugin which is causing the crash. Please use the above workarounds in the meantime to get around the issue.

**Comment by Alton09** [comment]
We found a fix for this issue! We are working on pushing a new release for the twilio-video-android SDK and will update this project accordingly.

**Comment by ayavilevich** [comment]
@shaunpanjabi this affected project of mine is using proguard but only in release configuration. The one I tried and failed when in an APK form was a debug build. Strange...

**Comment by azhararmar** [comment]
Faced the same issue with the react-native project, For some reason, when I ran the project from Android Studio it worked and when I ran it from CLI using `react-native run-android` it crashed, I then downgraded the gradle to following, and it started working again.

```
distributionUrl=https\://services.gradle.org/distributions/gradle-5.3.1-all.zip
com.android.tools.build:gradle:3.4.1
```

**Comment by Alton09** [comment]
New release is on the way. In the meantime, we found another workaround that seems to be the most affective. Add the below property to either the quickstartKotlin or quickstart gradle.properties file and it will resolve the crash.

```
android.enableDexingArtifactTransform.desugaring=false
```

**Comment by Alton09** [comment]
Refer to the Google issue [here](https://issuetracker.google.com/issues/140508065) for the latest update on this issue. Please use the workaround mentioned above to get around this issue for now. Google has fixed this issue in [this alpha release](https://android.googlesource.com/platform/tools/base/+/f7f446e6c304b035e347eccd181e2b6ee4b16d97#). Our change to the SDK ended up not having an effect as there was a false positive in our testing. I'll work on getting a pull request for this repo to add the workaround as well.

**Comment by zmrys** [comment]
I'm having this issuse too.

**Comment by andschdk** [comment]
I'm also facing this issue on Android 5.1.1 (API 22). Works fine on Android 8.1.0.
I'm able to make it work with the `android.enableDexingArtifactTransform.desugaring=false` workaround. Think this should be reopened?

Crash on `LocalVideoTrack.create`

```java.lang.NoSuchMethodError: No static method create()Lorg/webrtc/EglBase; in class Lorg/webrtc/EglBase; or its super classes (declaration of 'org.webrtc.EglBase' appears in /data/app/<bundle_id>-1/base.apk:classes3.dex)```

Kotlin version 1.3.31
Gradle plugin version 3.5.1
Gradle version 5.4.1

Android Studio 3.5.1
Build #AI-191.8026.42.35.5900203, built on September 25, 2019
JRE: 1.8.0_202-release-1483-b49-5587405 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.5

**Comment by Alton09** [comment]
@andschdk Thank you for calling this out! The issue is now reopened. I went ahead and tested with the newest Gradle plugin release (3.5.1) and it still crashes. We'll keep this issue open in the meantime until Google fixes it in a future release. To help higher prioritize [this issue](https://issuetracker.google.com/issues/140508065) on Google's end, please star it.

**Comment by hg5734** [comment]
Follow this link

https://github.com/react-native-webrtc/react-native-webrtc/issues/720

change the version of SDK

**Comment by aaalaniz** [comment]
According to the [Google issue](https://issuetracker.google.com/issues/140508065) this bug will be resolved in AGP 3.6.0 and AGP 4.0.0. The issue is marked as fixed in the issuetracker so I will close the issue here.

Thank you!

**Comment by rotmanyan** [comment]
If you want to fix it, then you can change on 'minSdkVersion 24' in this lib and also your app build.gradle.

**Comment by talhakosen** [comment]
`classpath 'com.android.tools.build:gradle:3.6.3'` fixed for me

**Comment by talhakosen** [comment]
classpath 'com.android.tools.build:gradle:3.6.3' works for me

**Comment by rmmcosta** [comment]
> New release is on the way. In the meantime, we found another workaround that seems to be the most affective. Add the below property to either the quickstartKotlin or quickstart gradle.properties file and it will resolve the crash.
> 
> ```
> android.enableDexingArtifactTransform.desugaring=false
> ```

Hi @Alton09  . Can you explain what will be the impact of setting this flag to false? Or can you provide any documentation about this flag?

**Comment by Alton09** [comment]
Hi @rmmcosta. We just recently removed this flag as part of this [pull request](https://github.com/twilio/video-quickstart-android/pull/527). It is no longer needed as of [3.6.0-beta05](https://issuetracker.google.com/issues/140508065#comment28) of the Android Gradle Plugin.
